### ISSUE TITLE
About the model of Segtron-XL base

### ISSUE THREAD

**Issue by xiaoxuanxuana** [rsvp-ai/segatron_aaai#1]
Hello, teacher, I am a graduate student in China. In order to study your paper in depth, I downloaded the model in Segtron-XL base on your github and tested it. But after testing, we found that this model is Transformer-XL base instead of Segatron-XL base. So I would like to ask, can you provide Segatron-XL base to help us study your paper in depth? Thank you!

**Comment by richardbaihe** [comment]
Hi @xiaoxuanxuana, thanks for pointing this out! 
I wasn't aware I uploaded a transformer-xl-base. I cannot find the original segatron-base-xl checkpoint, but I will train it again and notice you once I uploaded it.

**Comment by xiaoxuanxuana** [comment]
Thank you teacher for your help. We have also tried to train a model through your code. But it is true that our computer hardware performance is not enough, there is no way to train a model. Thank you again for your reply.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "He ***@***.***&gt;; 
发送时间: 2021年12月22日(星期三) 凌晨1:45
收件人: ***@***.***&gt;; 
抄送: "09017238 ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [rsvp-ai/segatron_aaai] About the model of Segtron-XL base (Issue #1)





 
Hi @xiaoxuanxuana, thanks for pointing this out!
 I wasn't aware I uploaded a transformer-xl-base. I cannot find the original segatron-base-xl checkpoint, but I will train it again and notice you once I uploaded it.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by richardbaihe** [comment]
> w

Hi @xiaoxuanxuana ,  I just updated the checkpoint of segatron-xl-base. The test ppl with eval_batch=10 is 21.825, which is slightly better than the number reported in our paper. Hope this can help you.
